services:
  judge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-judge
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=development
      - PORT=8080
    volumes:
      - .:/app  # Mount local code to the container for development
      - /sys/fs/cgroup:/sys/fs/cgroup:rw # Mount system cgroups to support Isolate
      - ./internal/submissions:/internal/submissions
    cap_add:
      - SYS_PTRACE  # Add capabilities required by Isolate for process tracing
      - SYS_ADMIN   # Add this to allow Isolate to clone processes and other admin tasks
      - NET_ADMIN   # Add this to manage network interfaces
    security_opt:
      - seccomp:unconfined # Disable seccomp for Isolate (it uses advanced kernel features)
    privileged: true  # Run the container in privileged mode to enable all capabilities

volumes:
  isolate-data:
    driver: local
