
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" # Mount Docker socket
    networks:
      - judge-net

  python-exec:
    build:
      context: docker/python
    image: python-exec
    networks:
      - judge-net
    command: tail -f /dev/null 

  cpp-exec:
    build:
      context: docker/cpp
    image: cpp-exec
    networks:
      - judge-net
    command: tail -f /dev/null 

networks:
  judge-net:
    driver: bridge
